import React,{useCallback,useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Activity,AlertCircle,CheckCircle2,Clock3,FileJson,RefreshCw,Server}from"lucide-react";
import"./styles.css";

async function request(path){const token=sessionStorage.getItem("pdr.webui.token")||"";const response=await fetch(path,{headers:token?{Authorization:`Bearer ${token}`}:{}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"请求失败");return data}
const statusText={running:"执行中",success:"成功",failed:"失败",cancelled:"已取消"};
const duration=node=>node.status==="running"?"执行中":`${(node.durationNanoseconds/1e6).toFixed(3)} ms`;
function Fields({values}){const entries=Object.entries(values||{});return entries.length?entries.map(([key,value])=><div className="field" key={key}><label>{key}</label><pre>{value}</pre></div>):<p className="none">无</p>}
function Detail({node}){if(!node)return <div className="empty"><FileJson size={28}/><p>点击流程节点查看详情</p></div>;return <div className="detail"><div className="detail-head"><span className={`status ${node.status}`}>{statusText[node.status]||node.status}</span><h2>{node.operation}</h2><p>{node.serviceName}{node.bundleName?` · ${node.bundleName}`:""}</p></div><dl><div><dt>耗时</dt><dd>{duration(node)}</dd></div><div><dt>主机 / 进程</dt><dd>{node.hostName} / {node.processId}</dd></div><div><dt>Trace ID</dt><dd>{node.traceId}</dd></div><div><dt>Span ID</dt><dd>{node.spanId}</dd></div></dl>{node.errorMessage&&<section><h3>失败信息</h3><div className="error"><b>{node.errorCode}</b><pre>{node.errorMessage}</pre></div></section>}<section><h3>传入参数</h3><Fields values={node.inputs}/></section><section><h3>传出参数</h3><Fields values={node.outputs}/></section><section><h3>关联日志</h3>{node.logs?.length?node.logs.map((log,index)=><div className="log" key={index}><header><b>{log.level}</b><time>{new Date(log.timestampUnixMicroseconds/1000).toLocaleTimeString()}</time></header><pre>{log.message}</pre><Fields values={log.fields}/></div>):<p className="none">无</p>}</section></div>}
function Flow({nodes,selected,onSelect}){const layout=useMemo(()=>{const byId=Object.fromEntries(nodes.map(node=>[node.spanId,node])),levels={},positions={};const depth=node=>{let value=0,current=node;const seen=new Set();while(current.parentSpanId&&byId[current.parentSpanId]&&!seen.has(current.parentSpanId)){seen.add(current.parentSpanId);current=byId[current.parentSpanId];value++}return value};nodes.forEach(node=>(levels[depth(node)]??=[]).push(node));Object.entries(levels).forEach(([level,list])=>list.forEach((node,index)=>positions[node.spanId]={x:35+Number(level)*260,y:35+index*125}));return{positions,width:Math.max(760,...Object.values(positions).map(p=>p.x+240)),height:Math.max(560,...Object.values(positions).map(p=>p.y+115))}},[nodes]);return <div className="flow" style={{width:layout.width,height:layout.height}}><svg viewBox={`0 0 ${layout.width} ${layout.height}`}>{nodes.filter(node=>layout.positions[node.parentSpanId]).map(node=>{const from=layout.positions[node.parentSpanId],to=layout.positions[node.spanId];return <path key={node.spanId} d={`M ${from.x+220} ${from.y+39} C ${from.x+244} ${from.y+39},${to.x-24} ${to.y+39},${to.x} ${to.y+39}`}/>} )}</svg>{nodes.map(node=>{const point=layout.positions[node.spanId];return <button key={node.spanId} className={`node ${node.status} ${selected?.spanId===node.spanId?"active":""}`} style={{left:point.x,top:point.y}} onClick={()=>onSelect(node)}><span>{statusText[node.status]||node.status}</span><b>{node.operation}</b><small>{node.serviceName}</small><small>{duration(node)}</small></button>})}</div>}
function App(){const[traces,setTraces]=useState([]),[traceId,setTraceId]=useState(""),[nodes,setNodes]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState("");const loadList=useCallback(async()=>{try{const data=await request("/api/v1/business-traces");setTraces(data.traces||[]);setTraceId(current=>current||data.traces?.[0]?.traceId||"");setError("")}catch(e){setError(e.message)}},[]);const loadTrace=useCallback(async id=>{if(!id)return;try{const data=await request(`/api/v1/business-traces/${encodeURIComponent(id)}`);setNodes(data.nodes||[]);setSelected(current=>data.nodes?.find(node=>node.spanId===current?.spanId)||null)}catch(e){setError(e.message)}},[]);useEffect(()=>{loadList();const timer=setInterval(loadList,2000);return()=>clearInterval(timer)},[loadList]);useEffect(()=>{loadTrace(traceId);const timer=setInterval(()=>loadTrace(traceId),2000);return()=>clearInterval(timer)},[traceId,loadTrace]);const active=traces.find(trace=>trace.traceId===traceId);return <div className="page"><header className="top"><div><span><Activity size={18}/></span><div><h1>OpenTelemetry 业务追踪</h1><p>业务执行流程、参数、状态、耗时与关联日志</p></div></div><button onClick={loadList}><RefreshCw size={16}/>刷新</button></header>{error&&<div className="banner"><AlertCircle size={17}/>{error}</div>}<main><aside className="traces"><h2>业务实例</h2>{traces.map(trace=><button key={trace.traceId} className={trace.traceId===traceId?"active":""} onClick={()=>{setTraceId(trace.traceId);setSelected(null)}}><span className={`status ${trace.status}`}>{trace.status==="success"?<CheckCircle2 size={13}/>:<Clock3 size={13}/>} {statusText[trace.status]||trace.status}</span><b>{trace.businessName}</b><small>{trace.businessInstanceId}</small><small>{trace.stepCount} 个节点 · {new Date(trace.startedUnixMicroseconds/1000).toLocaleString()}</small>{trace.failedOperation&&<em>失败于 {trace.failedOperation}</em>}</button>)}{!traces.length&&<div className="empty"><Activity/><p>暂无业务追踪</p></div>}</aside><section className="graph"><header><div><h2>{active?.businessName||"业务流程图"}</h2><p>{active?.businessInstanceId||"选择一个业务实例"}</p></div>{active&&<span className={`status ${active.status}`}>{statusText[active.status]||active.status}</span>}</header><div className="scroll"><Flow nodes={nodes} selected={selected} onSelect={setSelected}/></div></section><aside className="inspector"><h2><Server size={16}/>节点详情</h2><Detail node={selected}/></aside></main></div>}
createRoot(document.getElementById("root")).render(<App/>);
