subprocess.count = 3

subprocess.0.enabled = true
subprocess.0.name = qt3d-window-scene
subprocess.0.location = local
subprocess.0.path = pdr-qt3d-subprocess.exe
subprocess.0.workingDirectory = windows/window-scene
subprocess.0.argument.count = 3
subprocess.0.argument.0 = --window-worker
subprocess.0.argument.1 = --instance
subprocess.0.argument.2 = window-scene

subprocess.1.enabled = true
subprocess.1.name = qt3d-window-material
subprocess.1.location = local
subprocess.1.path = pdr-qt3d-subprocess.exe
subprocess.1.workingDirectory = windows/window-material
subprocess.1.argument.count = 3
subprocess.1.argument.0 = --window-worker
subprocess.1.argument.1 = --instance
subprocess.1.argument.2 = window-material

subprocess.2.enabled = true
subprocess.2.name = qt3d-window-device
subprocess.2.location = local
subprocess.2.path = pdr-qt3d-subprocess.exe
subprocess.2.workingDirectory = windows/window-device
subprocess.2.argument.count = 3
subprocess.2.argument.0 = --window-worker
subprocess.2.argument.1 = --instance
subprocess.2.argument.2 = window-device
