osp.bundleRepository = ${application.dir}bundles
osp.codeCache = ${application.dir}codeCache
osp.data = ${application.dir}data
osp.autoUpdateCodeCache = true
osp.sharedCodeCache = true

qt3d.scene = rotating-cube
qt3d.renderBackend = rhi
qt3d.frameIntervalMilliseconds = 16
