#!/usr/bin/env python3
"""Generate and verify repository CODEOWNERS from framework ownership contracts."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any

from framework_change_impact import load_catalog


PRINCIPAL = re.compile(
    r"^@[A-Za-z0-9](?:[A-Za-z0-9-]{0,38}[A-Za-z0-9])?"
    r"(?:/[A-Za-z0-9](?:[A-Za-z0-9_-]*[A-Za-z0-9])?)?$"
)


def _reviewers(value: Any, label: str) -> list[str]:
    if (not isinstance(value, list) or not value or
            any(not isinstance(item, str) or not PRINCIPAL.fullmatch(item)
                for item in value)):
        raise ValueError(f"{label} must contain valid GitHub user or team handles")
    if len(value) != len(set(value)):
        raise ValueError(f"{label} contains duplicate reviewers")
    return sorted(value, key=str.casefold)


def load_registry(path: Path, catalog: dict[str, Any]) -> dict[str, Any]:
    document = json.loads(path.read_text(encoding="utf-8"))
    if (set(document) != {"$schema", "schemaVersion", "product",
                         "defaultReviewers", "logicalOwners"} or
            not isinstance(document.get("$schema"), str) or
            not document["$schema"] or
            document.get("schemaVersion") != 1 or
            document.get("product") != "PocoDDSRuntimeRepositoryOwners" or
            not isinstance(document.get("logicalOwners"), dict)):
        raise ValueError("repository owner registry is malformed")
    default_reviewers = _reviewers(
        document.get("defaultReviewers"), "defaultReviewers"
    )
    logical = document["logicalOwners"]
    expected = {component["owner"] for component in catalog["components"]}
    actual = set(logical)
    missing = sorted(expected - actual)
    stale = sorted(actual - expected)
    if missing or stale:
        details = []
        if missing:
            details.append("missing=" + ",".join(missing))
        if stale:
            details.append("stale=" + ",".join(stale))
        raise ValueError("repository owner registry does not match catalog: " + " ".join(details))
    normalized = {
        owner: _reviewers(logical[owner], f"logicalOwners.{owner}")
        for owner in sorted(logical)
    }
    return {
        "schemaVersion": 1,
        "product": "PocoDDSRuntimeRepositoryOwners",
        "defaultReviewers": default_reviewers,
        "logicalOwners": normalized,
    }


def codeowners_pattern(rule: str) -> str:
    if any(character.isspace() for character in rule) or any(
            character in rule for character in ("#", "!", "[")
    ):
        raise ValueError(f"path rule cannot be represented safely in CODEOWNERS: {rule}")
    return "/" + rule


def render(catalog: dict[str, Any], registry: dict[str, Any]) -> str:
    lines = [
        "# Generated by tools/repository_ownership.py. Do not edit manually.",
        "# Sources: contracts/framework-components.json and contracts/repository-owners.json",
        "",
        "# Repository fallback: new or unclassified paths still require review",
        "* " + " ".join(sorted(registry["defaultReviewers"], key=str.casefold)),
        "",
        "# Framework-wide and repository governance paths",
    ]
    defaults = " ".join(sorted(registry["defaultReviewers"], key=str.casefold))
    for rule in sorted(catalog["globalPaths"]):
        lines.append(f"{codeowners_pattern(rule)} {defaults}")
    for component in sorted(catalog["components"], key=lambda item: item["id"]):
        lines.extend(["", f"# {component['id']} ({component['owner']})"])
        reviewers = " ".join(sorted(
            registry["logicalOwners"][component["owner"]], key=str.casefold
        ))
        for rule in sorted(component["paths"]):
            lines.append(f"{codeowners_pattern(rule)} {reviewers}")
    return "\n".join(lines) + "\n"


def load_inputs(catalog_path: Path, registry_path: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    catalog = load_catalog(catalog_path.resolve())
    registry = load_registry(registry_path.resolve(), catalog)
    return catalog, registry


def render_command(args: argparse.Namespace) -> int:
    try:
        catalog, registry = load_inputs(args.catalog, args.registry)
        output = args.output.resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render(catalog, registry), encoding="utf-8", newline="\n")
        print(
            "REPOSITORY_OWNERSHIP_RENDER_PASS "
            f"components={len(catalog['components'])} "
            f"logicalOwners={len(registry['logicalOwners'])}"
        )
        return 0
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as error:
        print(f"REPOSITORY_OWNERSHIP_ERROR: {error}", file=os.sys.stderr)
        return 1


def verify_command(args: argparse.Namespace) -> int:
    try:
        catalog, registry = load_inputs(args.catalog, args.registry)
        expected = render(catalog, registry)
        actual = args.codeowners.resolve().read_text(encoding="utf-8")
        if actual.replace("\r\n", "\n") != expected:
            raise ValueError(
                "CODEOWNERS is stale; regenerate it with repository_ownership.py render"
            )
        print(
            "REPOSITORY_OWNERSHIP_VERIFY_PASS "
            f"components={len(catalog['components'])} "
            f"logicalOwners={len(registry['logicalOwners'])}"
        )
        return 0
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as error:
        print(f"REPOSITORY_OWNERSHIP_ERROR: {error}", file=os.sys.stderr)
        return 1


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    commands = result.add_subparsers(dest="command", required=True)
    for name, handler in (("render", render_command), ("verify", verify_command)):
        command = commands.add_parser(name)
        command.add_argument("--catalog", type=Path, required=True)
        command.add_argument("--registry", type=Path, required=True)
        command.add_argument("--output" if name == "render" else "--codeowners",
                             type=Path, required=True)
        command.set_defaults(handler=handler)
    return result


if __name__ == "__main__":
    arguments = parser().parse_args()
    raise SystemExit(arguments.handler(arguments))
