if(NOT DEFINED PDR_DESTINATION)
    message(FATAL_ERROR "PDR_DESTINATION is required")
endif()
file(MAKE_DIRECTORY "${PDR_DESTINATION}")
if(DEFINED PDR_RUNTIME_DLLS AND NOT PDR_RUNTIME_DLLS STREQUAL "")
    string(REPLACE "|" ";" runtime_dlls "${PDR_RUNTIME_DLLS}")
    foreach(runtime_dll IN LISTS runtime_dlls)
        if(NOT runtime_dll STREQUAL "")
            get_filename_component(runtime_name "${runtime_dll}" NAME)
            file(COPY_FILE "${runtime_dll}" "${PDR_DESTINATION}/${runtime_name}"
                ONLY_IF_DIFFERENT)
        endif()
    endforeach()
endif()
