include_guard(GLOBAL)

function(_pdr_collect_buildsystem_targets directory output)
    get_property(local_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    set(result ${local_targets})
    get_property(subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(subdirectory IN LISTS subdirectories)
        _pdr_collect_buildsystem_targets("${subdirectory}" nested_targets)
        list(APPEND result ${nested_targets})
    endforeach()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(_pdr_json_escape value output)
    set(escaped "${value}")
    string(REPLACE "\\" "\\\\" escaped "${escaped}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\t" "\\t" escaped "${escaped}")
    set(${output} "${escaped}" PARENT_SCOPE)
endfunction()

function(_pdr_resolve_project_link_item value output_target output_unresolved)
    set(candidate "${value}")
    set(unresolved "")

    # These wrappers preserve a single target identity at configure time.
    foreach(wrapper LINK_ONLY BUILD_INTERFACE TARGET_NAME_IF_EXISTS TARGET_LINKER_FILE)
        if(candidate MATCHES "^\\$<${wrapper}:([^>]+)>$")
            set(candidate "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    if(candidate MATCHES "^\\$<INSTALL_INTERFACE:")
        set(candidate "")
    elseif(candidate MATCHES "\\$<")
        set(unresolved "${value}")
        set(candidate "")
    endif()

    set(resolved "")
    if(candidate AND TARGET "${candidate}")
        get_target_property(aliased_target "${candidate}" ALIASED_TARGET)
        if(aliased_target)
            set(candidate "${aliased_target}")
        endif()
        get_property(known_targets GLOBAL PROPERTY PDR_FRAMEWORK_KNOWN_TARGETS)
        if(candidate IN_LIST known_targets)
            set(resolved "${candidate}")
        endif()
    endif()

    set(${output_target} "${resolved}" PARENT_SCOPE)
    set(${output_unresolved} "${unresolved}" PARENT_SCOPE)
endfunction()

function(_pdr_resolve_include_item value output_item output_unresolved)
    set(candidate "${value}")
    set(unresolved "")
    if(candidate MATCHES
            "^\\$<TARGET_PROPERTY:([^,>]+),INTERFACE_INCLUDE_DIRECTORIES>$")
        set(property_target "${CMAKE_MATCH_1}")
        if(NOT TARGET "${property_target}")
            set(unresolved "${value}")
            set(candidate "")
        else()
            get_target_property(property_values "${property_target}"
                INTERFACE_INCLUDE_DIRECTORIES)
            if(NOT property_values)
                set(property_values "")
            endif()
            set(resolved_values "")
            set(unresolved_values "")
            foreach(property_value IN LISTS property_values)
                _pdr_resolve_include_item("${property_value}"
                    nested_resolved nested_unresolved)
                list(APPEND resolved_values ${nested_resolved})
                list(APPEND unresolved_values ${nested_unresolved})
            endforeach()
            set(${output_item} "${resolved_values}" PARENT_SCOPE)
            set(${output_unresolved} "${unresolved_values}" PARENT_SCOPE)
            return()
        endif()
    elseif(candidate MATCHES "^\\$<BUILD_INTERFACE:([^>]+)>$")
        set(candidate "${CMAKE_MATCH_1}")
    elseif(candidate MATCHES "^\\$<INSTALL_INTERFACE:")
        set(candidate "")
    elseif(candidate MATCHES "\\$<")
        set(unresolved "${value}")
        set(candidate "")
    endif()
    set(${output_item} "${candidate}" PARENT_SCOPE)
    set(${output_unresolved} "${unresolved}" PARENT_SCOPE)
endfunction()

function(pdr_write_framework_link_manifest output_file)
    _pdr_collect_buildsystem_targets("${CMAKE_SOURCE_DIR}" targets)
    list(REMOVE_DUPLICATES targets)
    list(SORT targets)
    set_property(GLOBAL PROPERTY PDR_FRAMEWORK_KNOWN_TARGETS "${targets}")

    get_filename_component(output_directory "${output_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    _pdr_json_escape("${CMAKE_SOURCE_DIR}" source_root)
    _pdr_json_escape("${CMAKE_BINARY_DIR}" build_root)
    _pdr_json_escape("${PDR_PROFILE}" profile)
    file(WRITE "${output_file}"
        "{\n  \"schemaVersion\": 1,\n"
        "  \"operation\": \"cmake-target-link-manifest\",\n"
        "  \"profile\": \"${profile}\",\n"
        "  \"sourceRoot\": \"${source_root}\",\n"
        "  \"buildRoot\": \"${build_root}\",\n"
        "  \"targets\": [\n")

    set(first_target TRUE)
    foreach(target IN LISTS targets)
        get_target_property(target_type "${target}" TYPE)
        get_target_property(source_directory "${target}" SOURCE_DIR)
        get_target_property(sources "${target}" SOURCES)
        if(NOT sources)
            set(sources "")
        endif()
        list(REMOVE_DUPLICATES sources)
        list(SORT sources)

        if(target_type STREQUAL "INTERFACE_LIBRARY")
            get_target_property(link_items "${target}" INTERFACE_LINK_LIBRARIES)
        else()
            get_target_property(link_items "${target}" LINK_LIBRARIES)
        endif()
        if(NOT link_items)
            set(link_items "")
        endif()

        set(dependencies "")
        set(unresolved_items "")
        foreach(link_item IN LISTS link_items)
            if(link_item STREQUAL "debug" OR link_item STREQUAL "optimized" OR
               link_item STREQUAL "general")
                continue()
            endif()
            _pdr_resolve_project_link_item("${link_item}" dependency unresolved)
            if(dependency AND NOT dependency STREQUAL target)
                list(APPEND dependencies "${dependency}")
            endif()
            if(unresolved)
                list(APPEND unresolved_items "${unresolved}")
            endif()
        endforeach()
        list(REMOVE_DUPLICATES dependencies)
        list(SORT dependencies)
        list(REMOVE_DUPLICATES unresolved_items)
        list(SORT unresolved_items)

        get_target_property(direct_include_items "${target}" INCLUDE_DIRECTORIES)
        get_target_property(interface_include_items "${target}" INTERFACE_INCLUDE_DIRECTORIES)
        if(NOT direct_include_items)
            set(direct_include_items "")
        endif()
        if(NOT interface_include_items)
            set(interface_include_items "")
        endif()
        set(include_directories "")
        set(unresolved_include_items "")
        foreach(include_item IN LISTS direct_include_items interface_include_items)
            _pdr_resolve_include_item("${include_item}" resolved_include unresolved_include)
            if(resolved_include)
                list(APPEND include_directories "${resolved_include}")
            endif()
            if(unresolved_include)
                list(APPEND unresolved_include_items "${unresolved_include}")
            endif()
        endforeach()
        list(REMOVE_DUPLICATES include_directories)
        list(SORT include_directories)
        list(REMOVE_DUPLICATES unresolved_include_items)
        list(SORT unresolved_include_items)

        _pdr_json_escape("${target}" escaped_target)
        _pdr_json_escape("${target_type}" escaped_type)
        _pdr_json_escape("${source_directory}" escaped_source_directory)
        if(first_target)
            set(first_target FALSE)
        else()
            file(APPEND "${output_file}" ",\n")
        endif()
        file(APPEND "${output_file}"
            "    {\"name\": \"${escaped_target}\", \"type\": \"${escaped_type}\", "
            "\"sourceDirectory\": \"${escaped_source_directory}\", \"sources\": [")

        set(first_source TRUE)
        foreach(source IN LISTS sources)
            _pdr_json_escape("${source}" escaped_source)
            if(first_source)
                set(first_source FALSE)
            else()
                file(APPEND "${output_file}" ", ")
            endif()
            file(APPEND "${output_file}" "\"${escaped_source}\"")
        endforeach()
        file(APPEND "${output_file}" "], \"dependencies\": [")

        set(first_dependency TRUE)
        foreach(dependency IN LISTS dependencies)
            _pdr_json_escape("${dependency}" escaped_dependency)
            if(first_dependency)
                set(first_dependency FALSE)
            else()
                file(APPEND "${output_file}" ", ")
            endif()
            file(APPEND "${output_file}" "\"${escaped_dependency}\"")
        endforeach()
        file(APPEND "${output_file}" "], \"unresolvedLinkItems\": [")

        set(first_unresolved TRUE)
        foreach(unresolved IN LISTS unresolved_items)
            _pdr_json_escape("${unresolved}" escaped_unresolved)
            if(first_unresolved)
                set(first_unresolved FALSE)
            else()
                file(APPEND "${output_file}" ", ")
            endif()
            file(APPEND "${output_file}" "\"${escaped_unresolved}\"")
        endforeach()
        file(APPEND "${output_file}" "], \"includeDirectories\": [")

        set(first_include TRUE)
        foreach(include_directory IN LISTS include_directories)
            _pdr_json_escape("${include_directory}" escaped_include_directory)
            if(first_include)
                set(first_include FALSE)
            else()
                file(APPEND "${output_file}" ", ")
            endif()
            file(APPEND "${output_file}" "\"${escaped_include_directory}\"")
        endforeach()
        file(APPEND "${output_file}" "], \"unresolvedIncludeItems\": [")

        set(first_unresolved_include TRUE)
        foreach(unresolved_include IN LISTS unresolved_include_items)
            _pdr_json_escape("${unresolved_include}" escaped_unresolved_include)
            if(first_unresolved_include)
                set(first_unresolved_include FALSE)
            else()
                file(APPEND "${output_file}" ", ")
            endif()
            file(APPEND "${output_file}" "\"${escaped_unresolved_include}\"")
        endforeach()
        file(APPEND "${output_file}" "]}")
    endforeach()
    file(APPEND "${output_file}" "\n  ]\n}\n")
endfunction()
