include_guard(GLOBAL)

function(_pdr_framework_json_boolean input output)
    if(${input})
        set(${output} true PARENT_SCOPE)
    else()
        set(${output} false PARENT_SCOPE)
    endif()
endfunction()

function(pdr_configure_framework_model output_variable)
    if(PDR_BUILD_LEGACY_RUNTIME AND PDR_BUILD_ROBOTICS_RUNTIME)
        set(PDR_FRAMEWORK_FAMILY "hybrid")
        set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Hybrid Runtime")
    elseif(PDR_BUILD_ROBOTICS_RUNTIME)
        set(PDR_FRAMEWORK_FAMILY "robotics")
        set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Robotics Runtime")
    elseif(PDR_BUILD_LEGACY_RUNTIME)
        set(PDR_FRAMEWORK_FAMILY "generic")
        if(PDR_HOST_MODEL STREQUAL "service")
            set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Edge Runtime")
        elseif(PDR_HOST_MODEL STREQUAL "desktop")
            set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Desktop Runtime")
        elseif(PDR_HOST_MODEL STREQUAL "static")
            set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Static Runtime")
        else()
            set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Runtime")
        endif()
    else()
        set(PDR_FRAMEWORK_FAMILY "core")
        set(PDR_FRAMEWORK_DISPLAY_NAME "PocoDDS Runtime Core")
    endif()

    set(PDR_FRAMEWORK_TRANSPORTS_JSON "")
    set(PDR_FRAMEWORK_BUILTIN_TRANSPORTS_JSON "")
    set(PDR_FRAMEWORK_EXTERNAL_TRANSPORTS_JSON "")
    foreach(transport IN LISTS PDR_RESOLVED_TRANSPORTS)
        if(PDR_FRAMEWORK_TRANSPORTS_JSON)
            string(APPEND PDR_FRAMEWORK_TRANSPORTS_JSON ", ")
        endif()
        string(APPEND PDR_FRAMEWORK_TRANSPORTS_JSON "\"${transport}\"")
        set(_pdr_transport_bucket PDR_FRAMEWORK_EXTERNAL_TRANSPORTS_JSON)
        if((transport STREQUAL "inproc" AND PDR_BUILD_RUNTIME_CORE) OR
           (transport STREQUAL "fastdds" AND PDR_BUILD_LEGACY_RUNTIME))
            set(_pdr_transport_bucket PDR_FRAMEWORK_BUILTIN_TRANSPORTS_JSON)
        endif()
        if(NOT "${${_pdr_transport_bucket}}" STREQUAL "")
            string(APPEND ${_pdr_transport_bucket} ", ")
        endif()
        string(APPEND ${_pdr_transport_bucket} "\"${transport}\"")
    endforeach()

    _pdr_framework_json_boolean(PDR_BUILD_RUNTIME_CORE PDR_FRAMEWORK_RUNTIME_CORE)
    _pdr_framework_json_boolean(PDR_BUILD_LEGACY_RUNTIME PDR_FRAMEWORK_LEGACY_RUNTIME)
    _pdr_framework_json_boolean(PDR_BUILD_ROBOTICS_RUNTIME PDR_FRAMEWORK_ROBOTICS_RUNTIME)
    if(PDR_BUILD_WEBUI OR PDR_BUILD_ROBOTICS_RUNTIME)
        set(PDR_FRAMEWORK_WEBUI true)
    else()
        set(PDR_FRAMEWORK_WEBUI false)
    endif()
    _pdr_framework_json_boolean(PDR_ENABLE_OBSERVABILITY PDR_FRAMEWORK_OBSERVABILITY)
    _pdr_framework_json_boolean(MYIOT_ENABLE_DATA_MODULES PDR_FRAMEWORK_DATA_MODULES)

    set(PDR_CAP_RUNTIME_OVERVIEW ${PDR_FRAMEWORK_LEGACY_RUNTIME})
    set(PDR_CAP_PROCESS_MANAGEMENT ${PDR_FRAMEWORK_LEGACY_RUNTIME})
    set(PDR_CAP_DEVICE_PROTOCOLS ${PDR_FRAMEWORK_LEGACY_RUNTIME})
    set(PDR_CAP_BUNDLE_GOVERNANCE ${PDR_FRAMEWORK_LEGACY_RUNTIME})
    set(PDR_CAP_RUNTIME_GOVERNANCE ${PDR_FRAMEWORK_LEGACY_RUNTIME})
    set(PDR_CAP_DIAGNOSTIC_TERMINAL ${PDR_FRAMEWORK_LEGACY_RUNTIME})
    if(PDR_BUILD_LEGACY_RUNTIME AND PDR_ENABLE_OBSERVABILITY)
        set(PDR_CAP_METRICS true)
        set(PDR_CAP_BUSINESS_TRACING true)
    else()
        set(PDR_CAP_METRICS false)
        set(PDR_CAP_BUSINESS_TRACING false)
    endif()
    set(PDR_CAP_ROBOTICS ${PDR_FRAMEWORK_ROBOTICS_RUNTIME})
    set(PDR_CAP_ROBOTICS_SIMULATION ${PDR_FRAMEWORK_ROBOTICS_RUNTIME})
    # robotics/ros2_ws is built separately by colcon. Selecting ros2 is not
    # evidence that the external adapter was built and deployed.
    set(PDR_CAP_ROBOTICS_ROS2 false)

    set(PDR_FRAMEWORK_NAVIGATION_JSON "")
    if(PDR_BUILD_LEGACY_RUNTIME)
        set(_pdr_navigation overview processes devices plugins governance terminal)
        if(PDR_ENABLE_OBSERVABILITY)
            list(INSERT _pdr_navigation 4 metrics)
            list(APPEND _pdr_navigation tracing)
        endif()
    elseif(PDR_BUILD_ROBOTICS_RUNTIME)
        set(_pdr_navigation robotics-overview robotics-missions robotics-traces)
    else()
        set(_pdr_navigation core-overview)
    endif()
    foreach(route IN LISTS _pdr_navigation)
        if(PDR_FRAMEWORK_NAVIGATION_JSON)
            string(APPEND PDR_FRAMEWORK_NAVIGATION_JSON ", ")
        endif()
        string(APPEND PDR_FRAMEWORK_NAVIGATION_JSON "\"${route}\"")
    endforeach()

    set(_pdr_framework_manifest "${CMAKE_BINARY_DIR}/pdr-framework-model.json")
    configure_file(
        "${CMAKE_SOURCE_DIR}/cmake/pdr-framework-model.json.in"
        "${_pdr_framework_manifest}"
        @ONLY)
    install(FILES "${_pdr_framework_manifest}"
        DESTINATION "${CMAKE_INSTALL_DATADIR}/PocoDDSRuntime")

    set(PDR_FRAMEWORK_FAMILY "${PDR_FRAMEWORK_FAMILY}" PARENT_SCOPE)
    set(PDR_FRAMEWORK_DISPLAY_NAME "${PDR_FRAMEWORK_DISPLAY_NAME}" PARENT_SCOPE)
    set(PDR_FRAMEWORK_MODEL_MANIFEST "${_pdr_framework_manifest}" PARENT_SCOPE)
    set(PDR_FRAMEWORK_RUNTIME_CORE "${PDR_FRAMEWORK_RUNTIME_CORE}" PARENT_SCOPE)
    set(PDR_FRAMEWORK_LEGACY_RUNTIME "${PDR_FRAMEWORK_LEGACY_RUNTIME}" PARENT_SCOPE)
    set(PDR_FRAMEWORK_ROBOTICS_RUNTIME "${PDR_FRAMEWORK_ROBOTICS_RUNTIME}" PARENT_SCOPE)
    set(PDR_FRAMEWORK_TRANSPORTS_JSON "${PDR_FRAMEWORK_TRANSPORTS_JSON}" PARENT_SCOPE)
endfunction()
