include_guard(GLOBAL)

get_filename_component(_pdr_source_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(PDR_DEPENDENCY_INSTALL_PREFIX "${_pdr_source_root}/build/install"
    CACHE PATH "Unified runtime and third-party installation prefix")
unset(_pdr_source_root)
list(PREPEND CMAKE_PREFIX_PATH "${PDR_DEPENDENCY_INSTALL_PREFIX}")
set(PDR_DEPENDENCY_CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${PDR_DEPENDENCY_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${PDR_DEPENDENCY_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON)

if(CMAKE_TOOLCHAIN_FILE)
    list(APPEND PDR_DEPENDENCY_CMAKE_ARGS
        "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}")
endif()

if(CMAKE_CROSSCOMPILING)
    list(APPEND PDR_DEPENDENCY_CMAKE_ARGS
        "-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}"
        "-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}"
        "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
        "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
        "-DCMAKE_SYSROOT=${CMAKE_SYSROOT}")
endif()
