if(NOT MODEL_MANIFEST OR NOT EXISTS "${MODEL_MANIFEST}")
    message(FATAL_ERROR "Framework model manifest was not generated: ${MODEL_MANIFEST}")
endif()
file(READ "${MODEL_MANIFEST}" document)
string(JSON schema_version GET "${document}" schemaVersion)
string(JSON family GET "${document}" framework family)
string(JSON model GET "${document}" framework model)
string(JSON profile GET "${document}" framework profile)
string(JSON navigation_count LENGTH "${document}" navigation)
string(JSON transport_count LENGTH "${document}" transports)
string(JSON builtin_count LENGTH "${document}" transportResolution builtIn)
string(JSON external_count LENGTH "${document}" transportResolution externalAdapters)
if(NOT schema_version EQUAL 1)
    message(FATAL_ERROR "Unsupported framework model schema: ${schema_version}")
endif()
if(NOT family MATCHES "^(generic|robotics|hybrid|core)$")
    message(FATAL_ERROR "Unsupported framework family: ${family}")
endif()
if(NOT model MATCHES "^(static|desktop|osp|service|robotics)$")
    message(FATAL_ERROR "Unsupported framework host model: ${model}")
endif()
if(NOT profile STREQUAL EXPECTED_PROFILE)
    message(FATAL_ERROR "Framework profile mismatch: expected ${EXPECTED_PROFILE}, got ${profile}")
endif()
if(navigation_count LESS 1)
    message(FATAL_ERROR "Framework model must expose at least one navigation entry")
endif()
math(EXPR resolved_transport_count "${builtin_count} + ${external_count}")
if(NOT resolved_transport_count EQUAL transport_count)
    message(FATAL_ERROR "Every selected transport must resolve to builtIn or externalAdapters")
endif()
message(STATUS "PDR_FRAMEWORK_MODEL_PASS family=${family} model=${model} profile=${profile}")
