set(required_files
    "${SOURCE_DIR}/contracts/schemas/component-template-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/component-template-transaction.schema.json"
    "${SOURCE_DIR}/contracts/schemas/runtime-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/process-desired-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/process-desired-state-lease.schema.json"
    "${SOURCE_DIR}/contracts/schemas/runtime-schema-contract.schema.json"
    "${SOURCE_DIR}/contracts/schemas/runtime-capability-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/schema-compatibility-catalog.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-model.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-components.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-dependency-boundary.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-link-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-link-dependency-boundary.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-link-dependency-matrix.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-component-build-groups.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-component-build-groups-validation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-build-execution-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-change-impact.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-ci-execution-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-recovery-matrix.schema.json"
    "${SOURCE_DIR}/contracts/schemas/framework-recovery-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/sdk-public-surface-snapshot.schema.json"
    "${SOURCE_DIR}/contracts/schemas/sdk-public-surface-compatibility.schema.json"
    "${SOURCE_DIR}/contracts/schemas/sdk-deprecation-catalog.schema.json"
    "${SOURCE_DIR}/contracts/schemas/sdk-deprecation-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/sdk-header-self-containment-plan.schema.json"
    "${SOURCE_DIR}/contracts/schemas/sdk-header-self-containment-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/repository-owners.schema.json"
    "${SOURCE_DIR}/contracts/framework-components.json"
    "${SOURCE_DIR}/contracts/framework-recovery-matrix.json"
    "${SOURCE_DIR}/contracts/repository-owners.json"
    "${SOURCE_DIR}/contracts/sdk-deprecations.json"
    "${SOURCE_DIR}/contracts/schemas/pdr-project.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-component.schema.json"
    "${SOURCE_DIR}/contracts/schemas/component-contract-conformance.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-capabilities.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-approval-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-approval-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-approval-signature.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-audit-record.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-audit-head.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-audit-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-audit-checkpoint.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-audit-checkpoint-signature.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-audit-checkpoint-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-plan.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-preflight.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-config-transaction.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-template-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-template-transaction.schema.json"
    "${SOURCE_DIR}/contracts/schemas/project-package-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/runtime-resource.schema.json"
    "${SOURCE_DIR}/contracts/schemas/service-contracts.schema.json"
    "${SOURCE_DIR}/contracts/schemas/configuration-participants.schema.json"
    "${SOURCE_DIR}/contracts/schemas/configuration-participant-contract-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/configuration-participant-baseline.schema.json"
    "${SOURCE_DIR}/contracts/configuration-participant-baseline.json"
    "${SOURCE_DIR}/contracts/schemas/configuration-key-lifecycle.schema.json"
    "${SOURCE_DIR}/contracts/schemas/configuration-key-lifecycle-contract-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/configuration-key-lifecycle-baseline.schema.json"
    "${SOURCE_DIR}/contracts/configuration-key-lifecycle-baseline.json"
    "${SOURCE_DIR}/contracts/schemas/service-contract-baseline.schema.json"
    "${SOURCE_DIR}/contracts/schemas/service-contract-graph.schema.json"
    "${SOURCE_DIR}/contracts/service-contract-baseline.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-package-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-package-signature.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-package-lock.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-package-resolution.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-consumer-catalog.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-upgrade-impact.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-impact-execution-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-impact-approval-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-impact-approval.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-impact-gate.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-pointer.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-operation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-resolution.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-runner-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-runner-attestation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-runner-attestation-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-gate-authorization-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-gate-authorization.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-gate-authorization-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-access-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-access-policy-v2.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-access-policy-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-access-policy-activation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-command.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-capacity.schema.json"
    "${SOURCE_DIR}/contracts/schemas/process-file-lease-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-lease-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-request-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-recovery.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-recovery-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-head.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-activation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-record.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-checkpoint.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-checkpoint-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-archive-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-archive-marker.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-archive-base.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-archive-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-audit-archive-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-recovery-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-recovery-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-standby-marker.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-standby-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-standby-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-grant.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-capability-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-conformance.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-migration-sync.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-migration.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-migration-transaction.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-migration-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-backend-migration-abort.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-artifact-store-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-artifact-reference.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-artifact-store-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-artifact-store-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-artifact-store-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-artifact-store-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-backend-config-reference.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-backend-config-resolver-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-backend-config-resolver-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-backend-config-resolver-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-backend-config-resolver-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-backend-config-resolver-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-config-reference.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-config-resolver-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-config-resolver-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-config-resolver-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-config-resolver-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-config-resolver-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-conformance-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-conformance-admission-bundle.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-conformance-attestation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-conformance-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-reference.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-provider-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-provider-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-provider-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-provider-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-provider-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-secret-provider-check.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-listing.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-check.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-pointer.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-state-operation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-current.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-current-check.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-state-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconciler-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconciler-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconciler-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconciler-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconciler-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconcile-journal.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconcile-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-reconcile-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-plan.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-executor-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-executor-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-executor-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-executor-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-executor-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-node-map.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-journal.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-report.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-fleet-state-pointer.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-wave-gate-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-wave-gate-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-wave-gate-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-wave-gate-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-wave-gate-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-control-authorizer-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-control-authorizer-capability-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-control-authorizer-capability-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-control-authorizer-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-adapter-catalog-control-authorizer-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-etcd-adapter-config.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-etcd-preflight.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-etcd-acceptance.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-binding.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-leader-activation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-fencing-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-drain-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-drain-status.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-handoff-evidence.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-handoff-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-drain-command.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-remote-drain-response.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-anchor-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-anchor.schema.json"
    "${SOURCE_DIR}/contracts/schemas/team-contract-registry-anchor-verification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/release-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/release-artifact-manifest.schema.json"
    "${SOURCE_DIR}/contracts/schemas/plugin-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-attestation.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-break-glass-request.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-break-glass-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-break-glass-audit.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-break-glass-preflight.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-break-glass-transaction.schema.json"
    "${SOURCE_DIR}/contracts/schemas/bundle-repository-break-glass-recovery.schema.json"
    "${SOURCE_DIR}/contracts/schemas/plugin-host-state.schema.json"
    "${SOURCE_DIR}/contracts/schemas/release-qualification.schema.json"
    "${SOURCE_DIR}/contracts/schemas/external-acceptance.schema.json"
    "${SOURCE_DIR}/contracts/schemas/external-approver-trust-policy.schema.json"
    "${SOURCE_DIR}/contracts/schemas/evidence-bundle.schema.json"
    "${SOURCE_DIR}/contracts/schemas/release-pipeline.schema.json"
    "${SOURCE_DIR}/contracts/component-templates/v1.json"
    "${SOURCE_DIR}/contracts/schema-registry/catalog.json"
    "${SOURCE_DIR}/contracts/schema-registry/baselines/pdr.runtime.topic-contract/1.0.0.json"
    "${SOURCE_DIR}/contracts/schema-registry/current/pdr.runtime.topic-contract.json"
    "${SOURCE_DIR}/contracts/capabilities/default-policy.json"
    "${SOURCE_DIR}/contracts/openapi/runtime.yaml"
    "${SOURCE_DIR}/contracts/asyncapi/runtime.yaml")
foreach(path IN LISTS required_files)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing contract file: ${path}")
    endif()
    file(READ "${path}" content)
    if(NOT content MATCHES "[Vv]ersion|\\$schema")
        message(FATAL_ERROR "Contract has no version/schema declaration: ${path}")
    endif()
endforeach()

if(NOT EXISTS "${SOURCE_DIR}/contracts/compatibility/sdk-surface-0.1.0.json")
    message(FATAL_ERROR "Missing installed SDK public surface compatibility baseline")
endif()

file(READ "${SOURCE_DIR}/config/pdr-runtime.properties" runtime_properties)
if(NOT EXISTS "${SOURCE_DIR}/config/pdr-production-identity.properties.example")
    message(FATAL_ERROR "Production identity overlay example is missing")
endif()
set(fastdds_deployment_profile
    "${SOURCE_DIR}/config/fastdds-deployment.properties.example")
if(NOT EXISTS "${fastdds_deployment_profile}")
    message(FATAL_ERROR "Fast DDS deployment profile example is missing")
endif()
file(READ "${fastdds_deployment_profile}" fastdds_deployment_content)
foreach(required_fastdds_key
        "profileVersion=1"
        "interfaceWhitelist="
        "initialPeers="
        "avoidBuiltinMulticast="
        "sharedMemory="
        "maxInitialPeersRange=")
    string(FIND "${fastdds_deployment_content}" "${required_fastdds_key}"
           fastdds_key_position)
    if(fastdds_key_position EQUAL -1)
        message(FATAL_ERROR
            "Fast DDS deployment profile is missing key: ${required_fastdds_key}")
    endif()
endforeach()
foreach(required_key
        "osp.web.server.host"
        "osp.web.server.port"
        "pdr.fastdds.domainId"
        "pdr.subprocess.shutdownTimeoutMilliseconds")
    string(FIND "${runtime_properties}" "${required_key} =" key_position)
    if(key_position EQUAL -1)
        message(FATAL_ERROR "Runtime configuration is missing required key: ${required_key}")
    endif()
endforeach()

file(READ "${SOURCE_DIR}/contracts/openapi/runtime.yaml" openapi)
foreach(required_path "/health/live" "/health/ready" "/health/detail")
    string(FIND "${openapi}" "${required_path}:" path_position)
    if(path_position EQUAL -1)
        message(FATAL_ERROR "OpenAPI is missing required path: ${required_path}")
    endif()
endforeach()
message(STATUS "CONTRACT_FILES_PASS")
