file(READ "${SOURCE_DIR}/CMakePresets.json" presets)
foreach(profile embedded edge-test server)
    string(JSON preset_count LENGTH "${presets}" configurePresets)
    math(EXPR last "${preset_count} - 1")
    set(found false)
    foreach(index RANGE 0 ${last})
        string(JSON name GET "${presets}" configurePresets ${index} name)
        if(name STREQUAL profile)
            set(found true)
            string(JSON declared_profile GET "${presets}" configurePresets ${index} cacheVariables PDR_PROFILE)
            if(NOT declared_profile STREQUAL profile)
                message(FATAL_ERROR "Preset ${profile} declares PDR_PROFILE=${declared_profile}")
            endif()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "Missing deployment profile preset: ${profile}")
    endif()
endforeach()
message(STATUS "DEPLOYMENT_PROFILES_PASS")
