cmake_minimum_required(VERSION 3.24)
project(PDRTransportConsumer LANGUAGES CXX)

set(transport_components)
if(PDR_TEST_MQTT_TRANSPORT)
    list(APPEND transport_components MQTTTransport)
endif()
if(PDR_TEST_FASTDDS_TRANSPORT)
    list(APPEND transport_components FastDDSTransport)
endif()
if(NOT transport_components)
    message(FATAL_ERROR "Transport consumer requires at least one installed Adapter")
endif()
find_package(PocoDDSRuntime CONFIG REQUIRED COMPONENTS ${transport_components})

add_executable(pdr-transport-consumer main.cpp)
if(PDR_TEST_MQTT_TRANSPORT)
    target_link_libraries(pdr-transport-consumer PRIVATE PocoDDS::MQTTTransport)
    target_compile_definitions(pdr-transport-consumer PRIVATE PDR_TEST_MQTT_TRANSPORT=1)
endif()
if(PDR_TEST_FASTDDS_TRANSPORT)
    target_link_libraries(pdr-transport-consumer PRIVATE PocoDDS::FastDDSTransport)
    target_compile_definitions(pdr-transport-consumer PRIVATE PDR_TEST_FASTDDS_TRANSPORT=1)
endif()
target_compile_features(pdr-transport-consumer PRIVATE cxx_std_17)
